# Generated by Django 2.1.1 on 2018-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
